#!/bin/bash
BACKUP="/data/backup"
OVERRIDES="/data/overrides"
PERMLOCK="/data/perm.lock"

if [ ! -f $PERMLOCK ]; then
  chown root:qqch /data
  chmod 755 /data
  touch $PERMLOCK
fi

if [ ! -d $BACKUP ]; then 
 mkdir -p $BACKUP
 chown -R root:qqch $BACKUP
 chmod -R 700 $BACKUP
fi

if [ ! -d $OVERRIDES ]; then 
 mkdir -p $OVERRIDES
 chown -R root:qqch $OVERRIDES
 chmod -R 700 $OVERRIDES
fi



