#!/bin/bash

mkdir -p /data/backup/mysql/
mysql --defaults-file=/root/my.cnf -e 'show databases' | while read dbname; do mysqldump --defaults-file=/root/my.cnf  --log-error="/data/backup/mysql/cron.error.log" -E  "$dbname" > "/data/backup/mysql/$dbname".sql; done

mysqldump --defaults-file=/root/my.cnf --log-error="/data/backup/mysql/cron.error.log" --add-drop-database -A  > /data/backup/mysql/all.sql 
cp /root/my.cnf /data/backup/mysql/root.cnf
cp /etc/mysql/debian.cnf /data/backup/mysql/debian.cnf
